// Code generated by protoc-gen-go. DO NOT EDIT.
// source: usercenter.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	usercenter.proto

It has these top-level messages:
	User
	UserAuth
	RegisterReq
	RegisterResp
	LoginReq
	LoginResp
	GetUserInfoReq
	GetUserInfoResp
	GetUserAuthByAuthKeyReq
	GetUserAuthByAuthKeyResp
	GetUserAuthByUserIdReq
	GetUserAuthyUserIdResp
	GenerateTokenReq
	GenerateTokenResp
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// model
type User struct {
	Id       int64  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Mobile   string `protobuf:"bytes,2,opt,name=mobile" json:"mobile,omitempty"`
	Nickname string `protobuf:"bytes,3,opt,name=nickname" json:"nickname,omitempty"`
	Sex      int64  `protobuf:"varint,4,opt,name=sex" json:"sex,omitempty"`
	Avatar   string `protobuf:"bytes,5,opt,name=avatar" json:"avatar,omitempty"`
	Info     string `protobuf:"bytes,6,opt,name=info" json:"info,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *User) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *User) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *User) GetSex() int64 {
	if m != nil {
		return m.Sex
	}
	return 0
}

func (m *User) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *User) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

type UserAuth struct {
	Id       int64  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	UserId   int64  `protobuf:"varint,2,opt,name=userId" json:"userId,omitempty"`
	AuthType string `protobuf:"bytes,3,opt,name=authType" json:"authType,omitempty"`
	AuthKey  string `protobuf:"bytes,4,opt,name=authKey" json:"authKey,omitempty"`
}

func (m *UserAuth) Reset()                    { *m = UserAuth{} }
func (m *UserAuth) String() string            { return proto.CompactTextString(m) }
func (*UserAuth) ProtoMessage()               {}
func (*UserAuth) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *UserAuth) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UserAuth) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *UserAuth) GetAuthType() string {
	if m != nil {
		return m.AuthType
	}
	return ""
}

func (m *UserAuth) GetAuthKey() string {
	if m != nil {
		return m.AuthKey
	}
	return ""
}

// req 、resp
type RegisterReq struct {
	Mobile   string `protobuf:"bytes,1,opt,name=mobile" json:"mobile,omitempty"`
	Nickname string `protobuf:"bytes,2,opt,name=nickname" json:"nickname,omitempty"`
	Password string `protobuf:"bytes,3,opt,name=password" json:"password,omitempty"`
	AuthKey  string `protobuf:"bytes,4,opt,name=authKey" json:"authKey,omitempty"`
	AuthType string `protobuf:"bytes,5,opt,name=authType" json:"authType,omitempty"`
}

func (m *RegisterReq) Reset()                    { *m = RegisterReq{} }
func (m *RegisterReq) String() string            { return proto.CompactTextString(m) }
func (*RegisterReq) ProtoMessage()               {}
func (*RegisterReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *RegisterReq) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *RegisterReq) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *RegisterReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *RegisterReq) GetAuthKey() string {
	if m != nil {
		return m.AuthKey
	}
	return ""
}

func (m *RegisterReq) GetAuthType() string {
	if m != nil {
		return m.AuthType
	}
	return ""
}

type RegisterResp struct {
	AccessToken  string `protobuf:"bytes,1,opt,name=accessToken" json:"accessToken,omitempty"`
	AccessExpire int64  `protobuf:"varint,2,opt,name=accessExpire" json:"accessExpire,omitempty"`
	RefreshAfter int64  `protobuf:"varint,3,opt,name=refreshAfter" json:"refreshAfter,omitempty"`
}

func (m *RegisterResp) Reset()                    { *m = RegisterResp{} }
func (m *RegisterResp) String() string            { return proto.CompactTextString(m) }
func (*RegisterResp) ProtoMessage()               {}
func (*RegisterResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *RegisterResp) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *RegisterResp) GetAccessExpire() int64 {
	if m != nil {
		return m.AccessExpire
	}
	return 0
}

func (m *RegisterResp) GetRefreshAfter() int64 {
	if m != nil {
		return m.RefreshAfter
	}
	return 0
}

type LoginReq struct {
	AuthType string `protobuf:"bytes,1,opt,name=authType" json:"authType,omitempty"`
	AuthKey  string `protobuf:"bytes,2,opt,name=authKey" json:"authKey,omitempty"`
	Password string `protobuf:"bytes,3,opt,name=password" json:"password,omitempty"`
}

func (m *LoginReq) Reset()                    { *m = LoginReq{} }
func (m *LoginReq) String() string            { return proto.CompactTextString(m) }
func (*LoginReq) ProtoMessage()               {}
func (*LoginReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *LoginReq) GetAuthType() string {
	if m != nil {
		return m.AuthType
	}
	return ""
}

func (m *LoginReq) GetAuthKey() string {
	if m != nil {
		return m.AuthKey
	}
	return ""
}

func (m *LoginReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResp struct {
	AccessToken  string `protobuf:"bytes,1,opt,name=accessToken" json:"accessToken,omitempty"`
	AccessExpire int64  `protobuf:"varint,2,opt,name=accessExpire" json:"accessExpire,omitempty"`
	RefreshAfter int64  `protobuf:"varint,3,opt,name=refreshAfter" json:"refreshAfter,omitempty"`
}

func (m *LoginResp) Reset()                    { *m = LoginResp{} }
func (m *LoginResp) String() string            { return proto.CompactTextString(m) }
func (*LoginResp) ProtoMessage()               {}
func (*LoginResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *LoginResp) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *LoginResp) GetAccessExpire() int64 {
	if m != nil {
		return m.AccessExpire
	}
	return 0
}

func (m *LoginResp) GetRefreshAfter() int64 {
	if m != nil {
		return m.RefreshAfter
	}
	return 0
}

type GetUserInfoReq struct {
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *GetUserInfoReq) Reset()                    { *m = GetUserInfoReq{} }
func (m *GetUserInfoReq) String() string            { return proto.CompactTextString(m) }
func (*GetUserInfoReq) ProtoMessage()               {}
func (*GetUserInfoReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *GetUserInfoReq) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetUserInfoResp struct {
	User *User `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
}

func (m *GetUserInfoResp) Reset()                    { *m = GetUserInfoResp{} }
func (m *GetUserInfoResp) String() string            { return proto.CompactTextString(m) }
func (*GetUserInfoResp) ProtoMessage()               {}
func (*GetUserInfoResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *GetUserInfoResp) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type GetUserAuthByAuthKeyReq struct {
	AuthKey  string `protobuf:"bytes,1,opt,name=authKey" json:"authKey,omitempty"`
	AuthType string `protobuf:"bytes,2,opt,name=authType" json:"authType,omitempty"`
}

func (m *GetUserAuthByAuthKeyReq) Reset()                    { *m = GetUserAuthByAuthKeyReq{} }
func (m *GetUserAuthByAuthKeyReq) String() string            { return proto.CompactTextString(m) }
func (*GetUserAuthByAuthKeyReq) ProtoMessage()               {}
func (*GetUserAuthByAuthKeyReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *GetUserAuthByAuthKeyReq) GetAuthKey() string {
	if m != nil {
		return m.AuthKey
	}
	return ""
}

func (m *GetUserAuthByAuthKeyReq) GetAuthType() string {
	if m != nil {
		return m.AuthType
	}
	return ""
}

type GetUserAuthByAuthKeyResp struct {
	UserAuth *UserAuth `protobuf:"bytes,1,opt,name=userAuth" json:"userAuth,omitempty"`
}

func (m *GetUserAuthByAuthKeyResp) Reset()                    { *m = GetUserAuthByAuthKeyResp{} }
func (m *GetUserAuthByAuthKeyResp) String() string            { return proto.CompactTextString(m) }
func (*GetUserAuthByAuthKeyResp) ProtoMessage()               {}
func (*GetUserAuthByAuthKeyResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *GetUserAuthByAuthKeyResp) GetUserAuth() *UserAuth {
	if m != nil {
		return m.UserAuth
	}
	return nil
}

type GetUserAuthByUserIdReq struct {
	UserId   int64  `protobuf:"varint,1,opt,name=userId" json:"userId,omitempty"`
	AuthType string `protobuf:"bytes,2,opt,name=authType" json:"authType,omitempty"`
}

func (m *GetUserAuthByUserIdReq) Reset()                    { *m = GetUserAuthByUserIdReq{} }
func (m *GetUserAuthByUserIdReq) String() string            { return proto.CompactTextString(m) }
func (*GetUserAuthByUserIdReq) ProtoMessage()               {}
func (*GetUserAuthByUserIdReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *GetUserAuthByUserIdReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *GetUserAuthByUserIdReq) GetAuthType() string {
	if m != nil {
		return m.AuthType
	}
	return ""
}

type GetUserAuthyUserIdResp struct {
	UserAuth *UserAuth `protobuf:"bytes,1,opt,name=userAuth" json:"userAuth,omitempty"`
}

func (m *GetUserAuthyUserIdResp) Reset()                    { *m = GetUserAuthyUserIdResp{} }
func (m *GetUserAuthyUserIdResp) String() string            { return proto.CompactTextString(m) }
func (*GetUserAuthyUserIdResp) ProtoMessage()               {}
func (*GetUserAuthyUserIdResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *GetUserAuthyUserIdResp) GetUserAuth() *UserAuth {
	if m != nil {
		return m.UserAuth
	}
	return nil
}

type GenerateTokenReq struct {
	UserId int64 `protobuf:"varint,1,opt,name=userId" json:"userId,omitempty"`
}

func (m *GenerateTokenReq) Reset()                    { *m = GenerateTokenReq{} }
func (m *GenerateTokenReq) String() string            { return proto.CompactTextString(m) }
func (*GenerateTokenReq) ProtoMessage()               {}
func (*GenerateTokenReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *GenerateTokenReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type GenerateTokenResp struct {
	AccessToken  string `protobuf:"bytes,1,opt,name=accessToken" json:"accessToken,omitempty"`
	AccessExpire int64  `protobuf:"varint,2,opt,name=accessExpire" json:"accessExpire,omitempty"`
	RefreshAfter int64  `protobuf:"varint,3,opt,name=refreshAfter" json:"refreshAfter,omitempty"`
}

func (m *GenerateTokenResp) Reset()                    { *m = GenerateTokenResp{} }
func (m *GenerateTokenResp) String() string            { return proto.CompactTextString(m) }
func (*GenerateTokenResp) ProtoMessage()               {}
func (*GenerateTokenResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *GenerateTokenResp) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *GenerateTokenResp) GetAccessExpire() int64 {
	if m != nil {
		return m.AccessExpire
	}
	return 0
}

func (m *GenerateTokenResp) GetRefreshAfter() int64 {
	if m != nil {
		return m.RefreshAfter
	}
	return 0
}

func init() {
	proto.RegisterType((*User)(nil), "pb.User")
	proto.RegisterType((*UserAuth)(nil), "pb.UserAuth")
	proto.RegisterType((*RegisterReq)(nil), "pb.RegisterReq")
	proto.RegisterType((*RegisterResp)(nil), "pb.RegisterResp")
	proto.RegisterType((*LoginReq)(nil), "pb.LoginReq")
	proto.RegisterType((*LoginResp)(nil), "pb.LoginResp")
	proto.RegisterType((*GetUserInfoReq)(nil), "pb.GetUserInfoReq")
	proto.RegisterType((*GetUserInfoResp)(nil), "pb.GetUserInfoResp")
	proto.RegisterType((*GetUserAuthByAuthKeyReq)(nil), "pb.GetUserAuthByAuthKeyReq")
	proto.RegisterType((*GetUserAuthByAuthKeyResp)(nil), "pb.GetUserAuthByAuthKeyResp")
	proto.RegisterType((*GetUserAuthByUserIdReq)(nil), "pb.GetUserAuthByUserIdReq")
	proto.RegisterType((*GetUserAuthyUserIdResp)(nil), "pb.GetUserAuthyUserIdResp")
	proto.RegisterType((*GenerateTokenReq)(nil), "pb.GenerateTokenReq")
	proto.RegisterType((*GenerateTokenResp)(nil), "pb.GenerateTokenResp")
}

func init() { proto.RegisterFile("usercenter.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 582 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x95, 0x4b, 0x6f, 0xd3, 0x40,
	0x10, 0xc7, 0x65, 0xe7, 0x81, 0x33, 0x49, 0xdb, 0x30, 0x2d, 0xc5, 0x32, 0x3d, 0x44, 0x2b, 0x0e,
	0x11, 0x12, 0xa9, 0x54, 0x24, 0x4e, 0x5c, 0x12, 0x81, 0xaa, 0x8a, 0x22, 0x84, 0x55, 0x2e, 0x88,
	0x8b, 0x93, 0x4c, 0x1c, 0xab, 0xad, 0xbd, 0xec, 0x3a, 0x90, 0x1c, 0xb8, 0x73, 0xe7, 0xd3, 0x72,
	0x43, 0xbb, 0x59, 0x27, 0xb6, 0x13, 0x23, 0x71, 0xe9, 0x6d, 0xe7, 0xe1, 0xf1, 0x6f, 0x66, 0xfe,
	0x6b, 0x43, 0x77, 0x21, 0x49, 0x4c, 0x28, 0x4e, 0x49, 0x0c, 0xb8, 0x48, 0xd2, 0x04, 0x6d, 0x3e,
	0x66, 0xbf, 0x2c, 0xa8, 0x7f, 0x96, 0x24, 0xf0, 0x10, 0xec, 0x68, 0xea, 0x5a, 0x3d, 0xab, 0x5f,
	0xf3, 0xed, 0x68, 0x8a, 0xa7, 0xd0, 0xbc, 0x4f, 0xc6, 0xd1, 0x1d, 0xb9, 0x76, 0xcf, 0xea, 0xb7,
	0x7c, 0x63, 0xa1, 0x07, 0x4e, 0x1c, 0x4d, 0x6e, 0xe3, 0xe0, 0x9e, 0xdc, 0x9a, 0x8e, 0x6c, 0x6c,
	0xec, 0x42, 0x4d, 0xd2, 0xd2, 0xad, 0xeb, 0x22, 0xea, 0xa8, 0xaa, 0x04, 0xdf, 0x83, 0x34, 0x10,
	0x6e, 0x63, 0x5d, 0x65, 0x6d, 0x21, 0x42, 0x3d, 0x8a, 0x67, 0x89, 0xdb, 0xd4, 0x5e, 0x7d, 0x66,
	0x73, 0x70, 0x14, 0xc9, 0x70, 0x91, 0xce, 0xf7, 0xd1, 0x28, 0xfc, 0xab, 0xa9, 0xa6, 0xa9, 0xf9,
	0xc6, 0x52, 0x34, 0xc1, 0x22, 0x9d, 0xdf, 0xac, 0xf8, 0x86, 0x26, 0xb3, 0xd1, 0x85, 0x47, 0xea,
	0xfc, 0x9e, 0x56, 0x9a, 0xa8, 0xe5, 0x67, 0x26, 0xfb, 0x6d, 0x41, 0xdb, 0xa7, 0x30, 0x92, 0x29,
	0x09, 0x9f, 0xbe, 0xe5, 0x7a, 0xb5, 0x2a, 0x7b, 0xb5, 0x4b, 0xbd, 0x7a, 0xe0, 0xf0, 0x40, 0xca,
	0x1f, 0x89, 0x98, 0x66, 0x6f, 0xce, 0xec, 0xea, 0x37, 0x17, 0x78, 0x1b, 0x45, 0x5e, 0xb6, 0x84,
	0xce, 0x16, 0x4a, 0x72, 0xec, 0x41, 0x3b, 0x98, 0x4c, 0x48, 0xca, 0x9b, 0xe4, 0x96, 0x62, 0x83,
	0x96, 0x77, 0x21, 0x83, 0xce, 0xda, 0x7c, 0xb7, 0xe4, 0x91, 0x20, 0x33, 0x9b, 0x82, 0x4f, 0xe5,
	0x08, 0x9a, 0x09, 0x92, 0xf3, 0xe1, 0x2c, 0x25, 0xa1, 0x59, 0x6b, 0x7e, 0xc1, 0xc7, 0xbe, 0x82,
	0x73, 0x9d, 0x84, 0x51, 0xac, 0x66, 0x91, 0x27, 0xb4, 0xaa, 0x27, 0x6a, 0xef, 0xf4, 0x55, 0x35,
	0x0d, 0xb6, 0x80, 0x96, 0xa9, 0xfe, 0xa0, 0x4d, 0xf5, 0xe0, 0xf0, 0x92, 0x52, 0xa5, 0xa8, 0xab,
	0x78, 0x96, 0xa8, 0xd6, 0x4a, 0xa2, 0x62, 0xe7, 0x70, 0x54, 0xc8, 0x90, 0x1c, 0xcf, 0xa0, 0xae,
	0x94, 0xa5, 0x93, 0xda, 0x17, 0xce, 0x80, 0x8f, 0x07, 0x2a, 0xee, 0x6b, 0x2f, 0xfb, 0x08, 0x4f,
	0xcd, 0x03, 0x4a, 0xa4, 0xa3, 0xd5, 0x70, 0xdd, 0xbd, 0xaa, 0x9d, 0x1b, 0x8d, 0x55, 0xbd, 0x72,
	0xbb, 0xb4, 0xf2, 0xb7, 0xe0, 0xee, 0x2f, 0x28, 0x39, 0xf6, 0xc1, 0x59, 0x98, 0x80, 0xc1, 0xe9,
	0x64, 0x38, 0xca, 0xe7, 0x6f, 0xa2, 0xec, 0x1a, 0x4e, 0x0b, 0x55, 0x74, 0x47, 0x53, 0x23, 0x6c,
	0x73, 0x6d, 0xac, 0xca, 0x6b, 0x53, 0x66, 0x1a, 0x15, 0xaa, 0x6d, 0x8a, 0xfd, 0x17, 0xd1, 0x0b,
	0xe8, 0x5e, 0x52, 0x4c, 0x22, 0x48, 0x49, 0x2f, 0xf5, 0x1f, 0x2c, 0xec, 0x27, 0x3c, 0x2e, 0xe5,
	0x3e, 0xa4, 0x4c, 0x2e, 0xfe, 0xd8, 0x00, 0xdb, 0x2f, 0x23, 0x3e, 0x87, 0xc6, 0x9d, 0x12, 0x2b,
	0xea, 0xd6, 0xb2, 0x5b, 0xe1, 0x1d, 0xe4, 0x2c, 0xc9, 0xf1, 0x25, 0x38, 0xc2, 0x5c, 0x55, 0x3c,
	0x52, 0xa1, 0xdc, 0xd7, 0xc4, 0xeb, 0x16, 0x1d, 0x92, 0xe3, 0x6b, 0x68, 0x87, 0x5b, 0xa1, 0x21,
	0xaa, 0x84, 0xa2, 0x36, 0xbd, 0xe3, 0x1d, 0x9f, 0xe4, 0xf8, 0x09, 0x4e, 0xc2, 0x3d, 0xf2, 0xc0,
	0x67, 0xb9, 0xe4, 0xb2, 0x12, 0xbd, 0xb3, 0xea, 0xa0, 0xe4, 0xf8, 0x01, 0x8e, 0xc3, 0x5d, 0xad,
	0xa0, 0xb7, 0xf3, 0xd0, 0x46, 0x44, 0x5e, 0x39, 0x96, 0x97, 0xc4, 0x1b, 0x38, 0x08, 0xf3, 0xcb,
	0xc3, 0x93, 0x75, 0x72, 0x71, 0xf7, 0xde, 0x93, 0x3d, 0x5e, 0xc9, 0x47, 0xcd, 0x2f, 0xf5, 0xc1,
	0x39, 0x1f, 0x8f, 0x9b, 0xfa, 0x7f, 0xf4, 0xea, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x81, 0xf5,
	0xc2, 0xc2, 0xa3, 0x06, 0x00, 0x00,
}
