// Code generated by goctl. DO NOT EDIT!
// Source: user.proto

package server

import (
	"context"

	"zero-demo/app/usercenter/cmd/rpc/internal/logic"
	"zero-demo/app/usercenter/cmd/rpc/internal/svc"
	"zero-demo/app/usercenter/cmd/rpc/pb/user"
)

type UserServiceServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedUserServiceServer
}

func NewUserServiceServer(svcCtx *svc.ServiceContext) *UserServiceServer {
	return &UserServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServiceServer) UserGet(ctx context.Context, in *user.UserGetReq) (*user.UserGetResp, error) {
	l := logic.NewUserGetLogic(ctx, s.svcCtx)
	return l.UserGet(in)
}

func (s *UserServiceServer) UserSave(ctx context.Context, in *user.UserSaveReq) (*user.UserSaveResp, error) {
	l := logic.NewUserSaveLogic(ctx, s.svcCtx)
	return l.UserSave(in)
}

func (s *UserServiceServer) UserDelete(ctx context.Context, in *user.UserDeleteReq) (*user.UserDeleteResp, error) {
	l := logic.NewUserDeleteLogic(ctx, s.svcCtx)
	return l.UserDelete(in)
}

func (s *UserServiceServer) UserUpdate(ctx context.Context, in *user.UserUpdateReq) (*user.UserUpdateResp, error) {
	l := logic.NewUserUpdateLogic(ctx, s.svcCtx)
	return l.UserUpdate(in)
}

func (s *UserServiceServer) UserSearch(ctx context.Context, in *user.UserSearchReq) (*user.UserSearchResp, error) {
	l := logic.NewUserSearchLogic(ctx, s.svcCtx)
	return l.UserSearch(in)
}
