// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

/*
Package user is a generated protocol buffer package.

It is generated from these files:
	user.proto

It has these top-level messages:
	UserGetReq
	UserGetResp
	UserSaveReq
	UserSaveResp
	UserDeleteReq
	UserDeleteResp
	UserUpdateReq
	UserUpdateResp
	UserSearchReq
	UserSearchResp
	UserItem
*/
package user

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UserGetReq struct {
	Id int64 `protobuf:"varint,1,opt,name=Id" json:"Id,omitempty"`
}

func (m *UserGetReq) Reset()                    { *m = UserGetReq{} }
func (m *UserGetReq) String() string            { return proto.CompactTextString(m) }
func (*UserGetReq) ProtoMessage()               {}
func (*UserGetReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *UserGetReq) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type UserGetResp struct {
	User *UserItem `protobuf:"bytes,1,opt,name=User" json:"User,omitempty"`
}

func (m *UserGetResp) Reset()                    { *m = UserGetResp{} }
func (m *UserGetResp) String() string            { return proto.CompactTextString(m) }
func (*UserGetResp) ProtoMessage()               {}
func (*UserGetResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *UserGetResp) GetUser() *UserItem {
	if m != nil {
		return m.User
	}
	return nil
}

type UserSaveReq struct {
}

func (m *UserSaveReq) Reset()                    { *m = UserSaveReq{} }
func (m *UserSaveReq) String() string            { return proto.CompactTextString(m) }
func (*UserSaveReq) ProtoMessage()               {}
func (*UserSaveReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type UserSaveResp struct {
}

func (m *UserSaveResp) Reset()                    { *m = UserSaveResp{} }
func (m *UserSaveResp) String() string            { return proto.CompactTextString(m) }
func (*UserSaveResp) ProtoMessage()               {}
func (*UserSaveResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type UserDeleteReq struct {
	Id int64 `protobuf:"varint,1,opt,name=Id" json:"Id,omitempty"`
}

func (m *UserDeleteReq) Reset()                    { *m = UserDeleteReq{} }
func (m *UserDeleteReq) String() string            { return proto.CompactTextString(m) }
func (*UserDeleteReq) ProtoMessage()               {}
func (*UserDeleteReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *UserDeleteReq) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type UserDeleteResp struct {
}

func (m *UserDeleteResp) Reset()                    { *m = UserDeleteResp{} }
func (m *UserDeleteResp) String() string            { return proto.CompactTextString(m) }
func (*UserDeleteResp) ProtoMessage()               {}
func (*UserDeleteResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type UserUpdateReq struct {
	Id int64 `protobuf:"varint,1,opt,name=Id" json:"Id,omitempty"`
}

func (m *UserUpdateReq) Reset()                    { *m = UserUpdateReq{} }
func (m *UserUpdateReq) String() string            { return proto.CompactTextString(m) }
func (*UserUpdateReq) ProtoMessage()               {}
func (*UserUpdateReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *UserUpdateReq) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type UserUpdateResp struct {
}

func (m *UserUpdateResp) Reset()                    { *m = UserUpdateResp{} }
func (m *UserUpdateResp) String() string            { return proto.CompactTextString(m) }
func (*UserUpdateResp) ProtoMessage()               {}
func (*UserUpdateResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type UserSearchReq struct {
	PageNumber int64 `protobuf:"varint,1,opt,name=PageNumber" json:"PageNumber,omitempty"`
	PageSize   int64 `protobuf:"varint,2,opt,name=PageSize" json:"PageSize,omitempty"`
}

func (m *UserSearchReq) Reset()                    { *m = UserSearchReq{} }
func (m *UserSearchReq) String() string            { return proto.CompactTextString(m) }
func (*UserSearchReq) ProtoMessage()               {}
func (*UserSearchReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *UserSearchReq) GetPageNumber() int64 {
	if m != nil {
		return m.PageNumber
	}
	return 0
}

func (m *UserSearchReq) GetPageSize() int64 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

type UserSearchResp struct {
	List  []*UserItem `protobuf:"bytes,1,rep,name=List" json:"List,omitempty"`
	Total int64       `protobuf:"varint,2,opt,name=Total" json:"Total,omitempty"`
}

func (m *UserSearchResp) Reset()                    { *m = UserSearchResp{} }
func (m *UserSearchResp) String() string            { return proto.CompactTextString(m) }
func (*UserSearchResp) ProtoMessage()               {}
func (*UserSearchResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *UserSearchResp) GetList() []*UserItem {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *UserSearchResp) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

type UserItem struct {
	Mobile   string `protobuf:"bytes,2,opt,name=Mobile" json:"Mobile,omitempty"`
	Nickname string `protobuf:"bytes,3,opt,name=Nickname" json:"Nickname,omitempty"`
	Sex      int64  `protobuf:"varint,4,opt,name=Sex" json:"Sex,omitempty"`
	Avatar   string `protobuf:"bytes,5,opt,name=Avatar" json:"Avatar,omitempty"`
	Info     string `protobuf:"bytes,6,opt,name=Info" json:"Info,omitempty"`
}

func (m *UserItem) Reset()                    { *m = UserItem{} }
func (m *UserItem) String() string            { return proto.CompactTextString(m) }
func (*UserItem) ProtoMessage()               {}
func (*UserItem) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *UserItem) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *UserItem) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *UserItem) GetSex() int64 {
	if m != nil {
		return m.Sex
	}
	return 0
}

func (m *UserItem) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *UserItem) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

func init() {
	proto.RegisterType((*UserGetReq)(nil), "pb.UserGetReq")
	proto.RegisterType((*UserGetResp)(nil), "pb.UserGetResp")
	proto.RegisterType((*UserSaveReq)(nil), "pb.UserSaveReq")
	proto.RegisterType((*UserSaveResp)(nil), "pb.UserSaveResp")
	proto.RegisterType((*UserDeleteReq)(nil), "pb.UserDeleteReq")
	proto.RegisterType((*UserDeleteResp)(nil), "pb.UserDeleteResp")
	proto.RegisterType((*UserUpdateReq)(nil), "pb.UserUpdateReq")
	proto.RegisterType((*UserUpdateResp)(nil), "pb.UserUpdateResp")
	proto.RegisterType((*UserSearchReq)(nil), "pb.UserSearchReq")
	proto.RegisterType((*UserSearchResp)(nil), "pb.UserSearchResp")
	proto.RegisterType((*UserItem)(nil), "pb.UserItem")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 392 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x93, 0xd1, 0x6f, 0xda, 0x30,
	0x10, 0xc6, 0x45, 0x02, 0x0c, 0x0e, 0xc8, 0xd8, 0x69, 0x9a, 0xa2, 0x68, 0xda, 0x90, 0x9f, 0xa6,
	0x49, 0x0b, 0x12, 0xfc, 0x05, 0x9b, 0x26, 0x6d, 0xd1, 0x36, 0x34, 0x25, 0xe3, 0x65, 0x6f, 0x0e,
	0x5c, 0xdb, 0xa8, 0x40, 0x4c, 0x1c, 0x50, 0x55, 0xf5, 0xbd, 0xff, 0x76, 0x65, 0x3b, 0x89, 0xa1,
	0xad, 0xfa, 0x96, 0xef, 0xbe, 0xfb, 0xce, 0x8e, 0x7f, 0x36, 0xc0, 0x41, 0x52, 0x11, 0x8a, 0x22,
	0x2f, 0x73, 0x74, 0x44, 0xca, 0xde, 0x03, 0x2c, 0x25, 0x15, 0x3f, 0xa8, 0x8c, 0x69, 0x8f, 0x1e,
	0x38, 0xd1, 0xda, 0x6f, 0x4d, 0x5a, 0x9f, 0xdc, 0xd8, 0x89, 0xd6, 0x6c, 0x0a, 0x83, 0xc6, 0x95,
	0x02, 0x27, 0xd0, 0x56, 0x52, 0x37, 0x0c, 0x66, 0xc3, 0x50, 0xa4, 0xa1, 0xd2, 0x51, 0x49, 0xdb,
	0x58, 0x3b, 0x6c, 0x64, 0x02, 0x09, 0x3f, 0x52, 0x4c, 0x7b, 0xe6, 0xc1, 0xd0, 0x4a, 0x29, 0xd8,
	0x47, 0x18, 0x29, 0xfd, 0x9d, 0x36, 0x54, 0xd2, 0x73, 0x0b, 0x8e, 0xc1, 0x3b, 0x6d, 0xb0, 0x91,
	0xa5, 0x58, 0xf3, 0x17, 0x23, 0x75, 0x83, 0x14, 0xec, 0x97, 0x89, 0x24, 0xc4, 0x8b, 0xd5, 0x95,
	0x8a, 0x7c, 0x00, 0xf8, 0xcb, 0x2f, 0x69, 0x71, 0xd8, 0xa6, 0xd5, 0xee, 0xdd, 0xf8, 0xa4, 0x82,
	0x01, 0xf4, 0x94, 0x4a, 0xb2, 0x5b, 0xf2, 0x1d, 0xed, 0x36, 0x9a, 0xfd, 0x34, 0xe3, 0xeb, 0x61,
	0xe6, 0x14, 0x7e, 0x67, 0xb2, 0xf4, 0x5b, 0x13, 0xf7, 0xe9, 0x29, 0x28, 0x07, 0xdf, 0x42, 0xe7,
	0x5f, 0x5e, 0xf2, 0x4d, 0x35, 0xcc, 0x08, 0x76, 0x07, 0xbd, 0xba, 0x0f, 0xdf, 0x41, 0xf7, 0x4f,
	0x9e, 0x66, 0x1b, 0xb3, 0x5e, 0x3f, 0xae, 0x94, 0xda, 0xc9, 0x22, 0x5b, 0x5d, 0xef, 0xf8, 0x96,
	0x7c, 0x57, 0x3b, 0x8d, 0xc6, 0x31, 0xb8, 0x09, 0xdd, 0xf8, 0x6d, 0x3d, 0x53, 0x7d, 0xaa, 0x29,
	0x5f, 0x8f, 0xbc, 0xe4, 0x85, 0xdf, 0x31, 0x53, 0x8c, 0x42, 0x84, 0x76, 0xb4, 0xbb, 0xc8, 0xfd,
	0xae, 0xae, 0xea, 0xef, 0xd9, 0xbd, 0x53, 0xa1, 0xa1, 0xe2, 0x98, 0xad, 0x08, 0x3f, 0xc3, 0xab,
	0x0a, 0x2d, 0x7a, 0xf5, 0x2f, 0x98, 0x5b, 0x10, 0xbc, 0x3e, 0xd3, 0x52, 0xe0, 0x17, 0xb3, 0x73,
	0x85, 0x11, 0x1b, 0xb3, 0x62, 0x1c, 0x8c, 0xcf, 0x0b, 0x52, 0xe0, 0xdc, 0xdc, 0x29, 0x03, 0x11,
	0xdf, 0xd4, 0x7e, 0x43, 0x3d, 0xc0, 0xc7, 0x25, 0x1b, 0x32, 0x18, 0x6d, 0xa8, 0xe1, 0x6e, 0x43,
	0x96, 0x74, 0x1d, 0x32, 0x70, 0x6c, 0xa8, 0x21, 0x6f, 0x43, 0x96, 0xdf, 0xb7, 0xc1, 0xff, 0x7e,
	0x38, 0x15, 0xe9, 0x54, 0xbd, 0x84, 0xb4, 0xab, 0x9f, 0xc2, 0xfc, 0x21, 0x00, 0x00, 0xff, 0xff,
	0xc1, 0xa7, 0x5d, 0xc4, 0x18, 0x03, 0x00, 0x00,
}
